In [77]:
from university_match import return_best_match

In [78]:
df = pd.read_csv('dataset/world-universities.csv')

In [79]:
query = "I went to University of British Columbia"

return_best_match(df, query)

,Country,Name,Website,percent_match
109,CA,University of Northern British Columbia,http://www.unbc.ca/,100
98,CA,University of British Columbia,http://www.ubc.ca/,100
11,CA,British Columbia Open University,http://www.bcou.ca/,100
132,CA,York University,http://www.yorku.ca/,80
67,CA,Quest University,http://www.questu.ca/,77
87,CA,Trent University,http://www.trentu.ca/,77
12,CA,Brock University,http://www.brocku.ca/,77
10,CA,British Columbia Institute of Technology,http://www.bcit.ca/,74
50,CA,McGill University,http://www.mcgill.ca/,74
0,CA,Acadia University,http://www.acadiau.ca/,74